# config.example.yaml

server:
  port: "2818"

key_manager:
  # type can be "local" or "vault"
  type: "local"

  local:
    # Directory to store local key files.
    # This is used only when key_manager.type is "local".
    key_dir: "./keys"
    # Password for encrypting/decrypting local keys
    password: ""

  vault:
    # Vault server address.
    # This is used only when key_manager.type is "vault".
    address: "http://127.0.0.1:8200"
    # Vault token for authentication.
    token: "root"
    # Path to the transit secrets engine in Vault.
    transit_path: "transit"
